# Generated by Django 4.2.5 on 2023-10-05 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_shops_loc_alter_shops_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, verbose_name='Товар')),
                ('group', models.CharField(max_length=100, verbose_name='Группа')),
                ('category', models.CharField(max_length=100, verbose_name='Категория')),
                ('subcategory', models.CharField(max_length=100, verbose_name='Подкатегория')),
                ('uom', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='SalesSub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.categories')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.shops')),
            ],
            options={
                'verbose_name': 'прогонзыы',
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('sales_type', models.IntegerField()),
                ('sales_units', models.IntegerField()),
                ('sales_units_promo', models.IntegerField(blank=True, null=True)),
                ('sales_rub', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sales_run_promo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.categories')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.shops')),
            ],
            options={
                'verbose_name': 'Информация',
                'verbose_name_plural': 'Информации',
            },
        ),
    ]
