version: '3.3'
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file:
      - .env

  backend:
    image: ivanmatveev/lenta_project:latest
    # build:
    #   context: ./
    #   dockerfile: Dockerfile
    restart: always
    volumes:
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - .env

volumes:
  db_value: